_target_: src.models.molecule_module.MoFlowModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.moflow.MoFlow
  atomic_list: [5, 6, 7, 8, 9, 14, 15, 16, 17, 27, 33, 34, 35, 53, 0]
  b_n_type: 4
  b_n_flow: 10
  b_n_block: 3
  b_n_squeeze: 19
  b_hidden_ch: [512, 512]
  b_affine: True
  b_conv_lu: 2
  a_n_node: 38
  a_n_type: 15
  a_hidden_gnn: [256]
  a_hidden_lin: [512, 64]
  a_n_flow: 38
  a_n_block: 3
  mask_row_size_list: [1]
  mask_row_stride_list: [1]
  a_affine: True
  learn_dist: 1
  noise_scale: 0.6

# compile model for faster training with pytorch 2.0
compile: false
