_target_: src.models.molecule_module.MoFlowModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.moflow.MoFlow
  # atomic_list: [5, 6, 7, 8, 9, 14, 15, 16, 17, 27, 33, 34, 35, 53, 0]
  # atomic_list: [6, 7, 8, 9, 0]
  atomic_list: [1, 5, 6, 7, 8, 9, 11, 13, 14, 15, 16, 17, 19, 24, 26, 27, 33, 34, 35, 53, 79, 0]
  b_n_type: 4
  b_n_flow: 10
  b_n_block: 1
  b_n_squeeze: 5
  b_hidden_ch: [128, 128]
  b_affine: True
  b_conv_lu: 1
  a_n_node: 200
  a_n_type: 22
  a_hidden_gnn: [64]
  a_hidden_lin: [128, 64]
  a_n_flow: 27
  a_n_block: 1
  mask_row_size_list: [1]
  mask_row_stride_list: [1]
  a_affine: True
  learn_dist: 1
  noise_scale: 0.6
  # enc_conv_dim: [[256, 128],128]
  # enc_linear_dim: [128]
  # dec_dim: [128, 128]

# compile model for faster training with pytorch 2.0
compile: false
